### ISSUE TITLE
Queue handler seems to be borked

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/CaTRoX_QWR#1]
I only looked because of the post on HA about a queue method not working and you linked to your code. I then saw comments about changes in v2 breaking stuff??? I'm just scratching my head at what your code is supposed to be doing??

I guess it's trying to determine the playlist index of each queue item to display in the playlist but it's not doing very well. Repro steps...

1) make sure foobar isn't playing
2) add multiple instances of the same track to a playlist.
3) right click the last one>Add to playback queue
4) your playlist view incorrectly highlights the first item with a little 1 presumably indicating this is the queued item.

If you reproduce these steps with jsplaylist-mod, you'd see they are correctly identified like this...

![queue](https://user-images.githubusercontent.com/34617027/36621980-cb3ddb62-18f2-11e8-9bd1-cd7e2a37f2df.gif)

You should be using `plman.FindPlaybackQueueItemIndex`.

**Comment by TheQwertiest** [comment]
Well, at the time I was trying to minimize performance impact on big playlists: to find all queued item in playlist with plman.FindPlaybackQueueItemIndex, one must iterate through all playlist items (instead of all queued items). I didn't get around testing if my workaround actually helped with performance, I will test it now though.
Thanks for bringing this to my attention again!

**Comment by TheQwertiest** [comment]
Regretfully, I was right:
**Test Code:**
```
function queue_init_1() {
    var queued_rows = [];
    var queue_contents = plman.GetPlaybackQueueHandles();
    if (!queue_contents.Count) {
        return;
    }

    var playlist_items =  plman.GetPlaylistItems(plman.ActivePlaylist);
    for (var i = 0; i < queue_contents.Count; ++i) {
        var cur_queue_item_idx = playlist_items.Find(queue_contents.Item(i));
        if (cur_queue_item_idx === -1) {
            continue;
        }

        var queue_item = {azaza: cur_queue_item_idx};
        // Here goes other code, which does not have impact on performance

        queued_rows.push(queue_item);
    }
}

function queue_init_2() {
    var queued_rows = [];

    var queue_contents = plman.GetPlaybackQueueHandles();
    if (!queue_contents.Count) {
        return;
    }

    var playlist_items =  plman.GetPlaylistItems(plman.ActivePlaylist);
    for (var i = 0; i < playlist_items.Count; ++i) {
        var queue_idx = plman.FindPlaybackQueueItemIndex(playlist_items.Item(i), cur_playlist_idx, i);
        if (queue_idx === -1) {
            continue;
        }

        var queue_item = {azaza: queue_idx};
        // Here goes other code, which does not have impact on performance

        queued_rows.push(queue_item);
    }
}

var profiler = fb.CreateProfiler("test");
queue_init_1();
console.log('queue_init_1: ', profiler.Time);

profiler.reset();
queue_init_2();
console.log(queue_init_2: ', profiler.Time);
```

**Queue size:** 64 items
**Test Results:**

**Playlist size:** 3549 items.
```
queue_init_1:  0
queue_init_2:  17
```

**Playlist size:** 28392 items.
```
queue_init_1:  1
queue_init_2:  181
```

I.e. first method has practically no impact on performance at all :\

**Comment by marc2k3** [comment]
I don't understand why you're iterating the whole handle list. Surely you just iterate the few that are actually on screen. I presume you do that when getting the title formatting for each row item?

**Comment by marc2k3** [comment]
Just did a quick test with 2 thousand items (yes my collections is that tiny!)...

```js
var test = fb.CreateProfiler();

var ap = plman.ActivePlaylist;
var items = plman.GetPlaylistItems(ap);
for (var i = 0; i < items.Count; i++) {
    console.log(fb.TitleFormat("%artist% - %title%").EvalWithMetadb(items.Item(i)));
}
test.Print();
```

That took 25ms...

Add in the code to get the queue index...

```js
var test = fb.CreateProfiler();

var ap = plman.ActivePlaylist;
var items = plman.GetPlaylistItems(ap);
for (var i = 0; i < items.Count; i++) {
    var queue_idx = plman.FindPlaybackQueueItemIndex(items.Item(i), ap, i);
    console.log(fb.TitleFormat("%artist% - %title%").EvalWithMetadb(items.Item(i)));
}
test.Print();
```

That took 30ms so adds 20% which seems bad.

But what if I add in another titleformat request...

```js
var test = fb.CreateProfiler();

var ap = plman.ActivePlaylist;
var items = plman.GetPlaylistItems(ap);
for (var i = 0; i < items.Count; i++) {
    var queue_idx = plman.FindPlaybackQueueItemIndex(items.Item(i), ap, i);
    console.log(fb.TitleFormat("%artist% - %title%").EvalWithMetadb(items.Item(i)));
    console.log(fb.TitleFormat("%tracknumber%").EvalWithMetadb(items.Item(i)));
}
test.Print();
```

That adds another 15ms!!!

Let's do it again...

```js
var test = fb.CreateProfiler();

var ap = plman.ActivePlaylist;
var items = plman.GetPlaylistItems(ap);
for (var i = 0; i < items.Count; i++) {
    var queue_idx = plman.FindPlaybackQueueItemIndex(items.Item(i), ap, i);
    console.log(fb.TitleFormat("%artist% - %title%").EvalWithMetadb(items.Item(i)));
    console.log(fb.TitleFormat("%tracknumber%").EvalWithMetadb(items.Item(i)));
    console.log(fb.TitleFormat("%length%").EvalWithMetadb(items.Item(i)));
}
test.Print();
```

As you might have guessed, that's yet another 15ms. So getting the queue index on the fly seems rather cheap by comparison.

**Comment by TheQwertiest** [comment]
Actually my playlist works a bit differently: 
Query results for tracks are saved ([code](https://github.com/TheQwertiest/CaTRoX_QWR/blob/master/theme/Scripts/Panel_Playlist.js#L3195)), i.e. all query evaluations are done only once (unless track info is changed of course). The increase in memory consumption is minuscule (even for huge playlists) compared to the total memory that fb2k uses. This is done this way to reduce CPU usage on scrolling, since, as you have noted, query evaluation is not really cheap.

Also plman.FindPlaybackQueueItemIndex used in this way solves only one part of the problem - it makes possible to differentiate the first inclusion of the queue item from other tracks with the same metadb; but it's still impossible to differentiate all the other inclusions of the said item. E.g. with the following queue that contains only tracks with the same metadb [track_1, track_2, track_3, track_1] I can't tell how many times track_1 is included in the queue, since FindPlaybackQueueItemIndex can't tell me if track_1 is encountered more than once.

**Comment by marc2k3** [comment]
What I'm suggesting is identical to how the default UI playlist behaves. I thought that might be desirable but obviously not...

![untitled](https://user-images.githubusercontent.com/34617027/36632053-03027928-1979-11e8-9cdd-987833049f4e.png)

**Comment by TheQwertiest** [comment]
It is desirable, but the problem is that I want this default behaviour as well:

![default](https://user-images.githubusercontent.com/4470278/36632549-f087ca94-1998-11e8-88e8-0b1d16c0e702.png)

And I don't know how to achieve that with FindPlaybackQueueItemIndex without iterating through the whole playlist =(

**Comment by marc2k3** [comment]
I might have to consider restoring the PlaybackQueueItem interface or come up with a better way to get the indexes.

**Comment by TheQwertiest** [comment]
Thanks!

**Comment by marc2k3** [comment]
I was considering a method returning an array of playlist index/item index pairs but have decided to restore `plman.GetPlaybackQueueContents`. The items will be read-only...

```
		plman.GetPlaybackQueueContents(); (VBArray)
		/*
		Returns a VBArray so you need to use .toArray() on the result.
		Each item of the array is an instance of IFbPlaybackQueueItem.
		*/

			interface IFbPlaybackQueueItem {
				Properties:
					Handle; (IFbMetadbHandle) (read)
					PlaylistIndex; (uint) (read)
					PlaylistItemIndex; (uint) (read)

				Methods:
					Dispose(); (void)
			}
```

**Comment by marc2k3** [comment]
https://github.com/marc2k3/foo_jscript_panel/commit/eb5b9f64a8dea13dc08cb01b6bc804352ecce989

**Comment by TheQwertiest** [comment]
That's some great news! Thanks!

**Comment by elia-is-me** [comment]
`fb.Titleformat` cost a lot. It 'll be better if you cache it before `for` loop. Like:
```
var tf = fb.titleformat('xxx');
for (;;) {
    fb.trace(tf.evalwithmetadb(some_metadb);
}
```

**Comment by TheQwertiest** [comment]
? 
What part of the code are you talking about? =)

**Comment by TheQwertiest** [comment]
Oh, I see, that might really help with playlist initialization speed!

About using %path% : actually I've replaced it with RawPath not so long ago :D

**Comment by marc2k3** [comment]
You still have `%path%` in your playlist script. Obviously it's different from RawPath as well.

**Comment by TheQwertiest** [comment]
Improved initialized speed by 50%! Nice!

**Comment by marc2k3** [comment]
This might improve a bit more performance if you can make use of it...

https://github.com/marc2k3/foo_jscript_panel/commit/223eb1756ac61cfa79f0ae226af5e21476513253

**Comment by TheQwertiest** [comment]
I'm sure it will be useful sooner than later due fb.titleformat correct usage revelations =)
