### ISSUE TITLE
Allow for UI Hacks's Portability

### ISSUE THREAD

**Issue by ImportTaste** [TheQwertiest/CaTRoX_QWR#10]
UI Hacks has an option to load a fonts folder on startup, rather than relying on the fonts installed on the system. Because I use foobar2000 on my thumbstick, I wanted to take advantage of this for this theme. However, despite the plugin reporting that the fonts in the `.\fonts` folder were loaded successfully, foobar2000 still crashes on startup if the fonts are not installed on the system.

**Comment by TheQwertiest** [comment]
That's just the way `foo_ui_hacks` works: you can load additional fonts, but you can't check if they are actually available on the system.
