### ISSUE TITLE
Theme completely broken

### ISSUE THREAD

**Issue by ItsMeAubey** [TheQwertiest/CaTRoX_QWR#11]
Followed install instructions *to the letter*. I have previously used this theme on three other foobar installs so I have no idea what is going on here. 

```
Error: JScript Panel v2.1.4 (Thumbs)
JavaScript runtime error:
'_' is undefined
File: <main>
Line: 9, Col: 1
<source text only available at compile time>
```

![image](https://user-images.githubusercontent.com/35206674/99019806-289aff00-252b-11eb-92b7-2b6d035696d0.png)

**Comment by Balzhur** [comment]
I had similar errors when I put theme not into 'CaTRoX' directory but into differently named one. 'CaTRoX' theme path is hardcoded in the supplied theme.fcl

**Comment by EddieEldridge** [comment]
Did either of you ever resolve this? I'm getting the same error

**Comment by Star-Trails** [comment]
+1

**Comment by TheQwertiest** [comment]
Use v5.0.0

**Comment by ItsMeAubey** [comment]
Thank you!
