### ISSUE TITLE
Add quick rating

### ISSUE THREAD

**Issue by a1waysbeta** [TheQwertiest/CaTRoX_QWR#15]
Similar to jssp, you can quickly rate songs by clicking within the playlist, instead of just showing the song rating. Or add ratings to the top title bar or bottom of the window to quickly rate the song being played.

**Comment by TheQwertiest** [comment]
Already there :)
Double click on the desired rating on the track in the playlist and it will be changed accordingly.

**Comment by jeannela2019** [comment]
it's catrox 's original design that double clicking instead of single clicking to toggle/set ratings.

**Comment by a1waysbeta** [comment]
Sorry for the two stupid questions in a row. It doesn't support high dpi yet, it's small overall, and I haven't bothered to delve into the features that are already there.
