### ISSUE TITLE
Adding a switch to the visualization panel

### ISSUE THREAD

**Issue by a1waysbeta** [TheQwertiest/CaTRoX_QWR#16]
Add a switch to turn the bottom visualization panel on or off. or can the visualization panel be moved to the left sub-panel, for example under the properties panel?
![Screenshot_1 - 副本](https://user-images.githubusercontent.com/11453148/149783581-c898749b-32f4-46bb-88b9-8ad9e7349c47.jpg)

**Comment by TheQwertiest** [comment]
> Add a switch to turn the bottom visualization panel on or off

Already there :)
Right click on seekbar > `Show music spectrum`
