### ISSUE TITLE
Library Tree hang in CaTRoX while rating songs with Top Rated filter on

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/CaTRoX_QWR#2]
I couldn't actually reproduce the issue you described. But I have had a stackoverflow hang in other circumstances & suspect it might be the same issue.

I attach Library Tree 1.4 beta. Perhaps you could check to see if it resolves the issue.
[Library Tree 1.4 beta.txt](https://github.com/TheQwertiest/CaTRoX_QWR/files/1753532/Library.Tree.1.4.beta.txt)

**Comment by TheQwertiest** [comment]
Yup, the hang is gone. Thanks!

**Comment by TheQwertiest** [comment]
I will replace the script in the theme, only once you release it officially though :P
